/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baseaplication;

import java.awt.Color;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ZevusBloxk
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Tugas
     */
    String background_toogle = "white"; 
    ImageIcon bg = new ImageIcon(getClass().getResource("/Src/Form/Netbean W Form.jpg"));
    String menu1_status = "closed";   
    String menu2_status = "closed";
    String toolbar_lock = "false";
    ImageIcon lock_toogle = new ImageIcon(getClass().getResource("/Src/Images/Icons/unlock.png"));
    int xmouse;
    int ymouse;
    
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        load_Layout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void load_Layout(){
        background.setIcon(bg);
        close.setLocation(940, 5);
        close.setSize(50, 50);
        minimize.setLocation(830, 5);
        minimize.setSize(50, 50);
        switch_Theme.setLocation(720, 5);
        switch_Theme.setLocation(50, 50);
        drag.setLocation(0, 0);
        drag.setSize(1000, 50);
        menu1.setVisible(false);
        menu1.setLocation(0, 80);
        menu2.setLocation(30, 80);
        menu2.setVisible(false);
        menu1.setBackground(Color.decode("#ffffff"));
        toolbar_menu.setVisible(false);
        tb_lock_toogle.setIcon(lock_toogle);
//        background.getComponent(0).setForeground(Color.yellow);
//        getContentPane().setForeground(Color.yellow);
    }
    void closeMenuBar(){
        menu1.setVisible(false);
        menu2.setVisible(false);
        menu1_status = "closed";
        menu2_status = "closed";
        
    }
    void exit(){
        System.exit(0);
    }
    void darkTheme(){ 
        bg = new ImageIcon(getClass().getResource("/Src/Form/Netbean B Form.jpg"));
        background.setIcon(bg);
        background_toogle = "black";
        content.setBackground(Color.decode("#5D686E"));
        menu_file.setForeground(Color.white);
        menu_edit.setForeground(Color.white);
        //MenuBar Background Color
        menu1.setBackground(Color.decode("#2C3846"));
        //Menu Options
        menu1Option1.setBackground(Color.decode("#2C3846"));
        menu2.setBackground(Color.decode("#2C3846"));
        //Menu Options
        //MenuBar Font Color
        menu1.setForeground(Color.decode("#ffffff"));
        //Menu Options
        m1o1Text.setForeground(Color.decode("#ffffff"));
        m1o1Shortcut.setForeground(Color.decode("#ffffff"));
        menu2.setForeground(Color.decode("#ffffff"));
        //Menu Options
        //toolbar
        toolbar_menu.setBackground(Color.decode("#4C4C61"));
        Toolbar_open.setForeground(Color.decode("#ffffff"));
    }
    void lightTheme(){
        bg = new ImageIcon(getClass().getResource("/Src/Form/Netbean W Form.jpg"));
        background.setIcon(bg);
        background_toogle = "white";
        content.setBackground(Color.decode("#ffffff"));
        menu_file.setForeground(Color.black);
        menu_edit.setForeground(Color.black);
        //MenuBar Background Color
        menu1.setBackground(Color.decode("#ffffff"));
        //Menu Options
        menu1Option1.setBackground(Color.decode("#ffffff"));
        menu2.setBackground(Color.decode("#ffffff"));
        //Menu Options
        //MenuBar Font Color
        menu1.setForeground(Color.decode("#0"));
        //Menu options
        m1o1Text.setForeground(Color.decode("#0"));
        m1o1Shortcut.setForeground(Color.decode("#0"));
        menu2.setForeground(Color.decode("#0"));
        //Menu Options
        //toolbar
        toolbar_menu.setBackground(Color.decode("#ffffff"));
        Toolbar_open.setForeground(Color.decode("#0"));
    }

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        switch_Theme = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        menubar = new javax.swing.JToolBar();
        menu_file = new javax.swing.JButton();
        menu_edit = new javax.swing.JButton();
        menu1 = new javax.swing.JPanel();
        menu1Option1 = new javax.swing.JPanel();
        m1o1Text = new javax.swing.JLabel();
        m1o1Shortcut = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        toolbar_menu = new javax.swing.JPanel();
        tb_lock_toogle = new javax.swing.JLabel();
        toolbar_button = new javax.swing.JToolBar();
        Toolbar_open = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Src/Images/Logo/Logo.png")).getImage());
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 5, 50, 50));

        switch_Theme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        switch_Theme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                switch_ThemeMouseReleased(evt);
            }
        });
        getContentPane().add(switch_Theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 5, 50, 50));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 5, 50, 50));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dragMouseReleased(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        menubar.setBackground(new java.awt.Color(255, 255, 255));
        menubar.setFloatable(false);
        menubar.setRollover(true);

        menu_file.setText("File");
        menu_file.setFocusable(false);
        menu_file.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_file.setMinimumSize(new java.awt.Dimension(40, 21));
        menu_file.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fileActionPerformed(evt);
            }
        });
        menubar.add(menu_file);

        menu_edit.setText("Edit");
        menu_edit.setFocusable(false);
        menu_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_edit.setMinimumSize(new java.awt.Dimension(40, 21));
        menu_edit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_editActionPerformed(evt);
            }
        });
        menubar.add(menu_edit);

        getContentPane().add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 30));

        menu1.setBackground(new java.awt.Color(255, 255, 255));
        menu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu1Option1.setBackground(new java.awt.Color(255, 255, 255));
        menu1Option1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menu1Option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu1Option1MouseReleased(evt);
            }
        });
        menu1Option1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m1o1Text.setText("Exit");
        menu1Option1.add(m1o1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        m1o1Shortcut.setText("alt+f4");
        menu1Option1.add(m1o1Shortcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1Option1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addComponent(menu1Option1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 140));

        menu2.setBackground(new java.awt.Color(255, 255, 255));
        menu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 140));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contentMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1000, 540));

        toolbar_menu.setBackground(new java.awt.Color(255, 255, 255));
        toolbar_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toolbar_menuMouseExited(evt);
            }
        });

        tb_lock_toogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Images/Icons/unlock.png"))); // NOI18N
        tb_lock_toogle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_lock_toogleMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_lock_toogleMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout toolbar_menuLayout = new javax.swing.GroupLayout(toolbar_menu);
        toolbar_menu.setLayout(toolbar_menuLayout);
        toolbar_menuLayout.setHorizontalGroup(
            toolbar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbar_menuLayout.createSequentialGroup()
                .addContainerGap(930, Short.MAX_VALUE)
                .addComponent(tb_lock_toogle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toolbar_menuLayout.setVerticalGroup(
            toolbar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbar_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_lock_toogle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(toolbar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 80));

        toolbar_button.setFloatable(false);
        toolbar_button.setRollover(true);

        Toolbar_open.setText("Toolbar |V|");
        Toolbar_open.setFocusable(false);
        Toolbar_open.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Toolbar_open.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Toolbar_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Toolbar_openActionPerformed(evt);
            }
        });
        toolbar_button.add(Toolbar_open);

        getContentPane().add(toolbar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Form/Netbean W Form.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fileActionPerformed
        // TODO add your handling code here:
        menu2_status = "closed";
        menu2.setVisible(false);
        if (menu1_status == "closed") {
            menu1.setVisible(true);
            menu1_status = "opened";
        } else {
            menu1.setVisible(false);
            menu1_status = "closed";
        }
    }//GEN-LAST:event_menu_fileActionPerformed

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_dragMouseDragged

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_closeMouseReleased

    private void switch_ThemeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_ThemeMouseReleased
        // TODO add your handling code here:
        closeMenuBar();
        if (background_toogle == "white") {
            darkTheme();
        }else if (background_toogle == "black") {
            lightTheme();
        }
    }//GEN-LAST:event_switch_ThemeMouseReleased

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        // TODO add your handling code here:
        closeMenuBar();
        this.setExtendedState(MainMenu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void menu_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_editActionPerformed
        // TODO add your handling code here:
        menu1_status = "closed";
        menu1.setVisible(false);
        if (menu2_status == "closed") {
            menu2.setVisible(true);
            menu2_status = "opened";

        } else {
            menu2.setVisible(false);
            menu2_status = "closed";
        }
    }//GEN-LAST:event_menu_editActionPerformed

    private void menu1Option1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1Option1MouseReleased
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_menu1Option1MouseReleased

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        ImageIcon closeHover = new ImageIcon(getClass().getResource("/Src/Images/Icons/close.png"));
        close.setIcon(closeHover);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setIcon(null);
    }//GEN-LAST:event_closeMouseExited

    private void contentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMouseReleased
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_contentMouseReleased

    private void Toolbar_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Toolbar_openActionPerformed
        // TODO add your handling code here:
        toolbar_menu.setVisible(true);
    }//GEN-LAST:event_Toolbar_openActionPerformed

    private void toolbar_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolbar_menuMouseExited
        // TODO add your handling code here:
        if (toolbar_lock == "false") {
            toolbar_menu.setVisible(false);
        }
    }//GEN-LAST:event_toolbar_menuMouseExited

    private void tb_lock_toogleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_lock_toogleMouseReleased
        // TODO add your handling code here:
        if (toolbar_lock == "true") {
            lock_toogle = new ImageIcon(getClass().getResource("/Src/Images/Icons/unlock.png"));
            toolbar_lock = "false";
            tb_lock_toogle.setIcon(lock_toogle);
//            content.setSize(content.getSize().width, content.getSize().height+toolbar_menu.getSize().height);
        }else{
            lock_toogle = new ImageIcon(getClass().getResource("/Src/Images/Icons/lock.png"));
            toolbar_lock = "true";
            tb_lock_toogle.setIcon(lock_toogle);
        }
    }//GEN-LAST:event_tb_lock_toogleMouseReleased

    private void tb_lock_toogleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_lock_toogleMouseEntered
        // TODO add your handling code here:
        toolbar_menu.setVisible(true);
    }//GEN-LAST:event_tb_lock_toogleMouseEntered

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_formMouseReleased

    private void dragMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseReleased
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_dragMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Toolbar_open;
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JPanel content;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel m1o1Shortcut;
    private javax.swing.JLabel m1o1Text;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu1Option1;
    private javax.swing.JPanel menu2;
    private javax.swing.JButton menu_edit;
    private javax.swing.JButton menu_file;
    private javax.swing.JToolBar menubar;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel switch_Theme;
    private javax.swing.JLabel tb_lock_toogle;
    private javax.swing.JToolBar toolbar_button;
    private javax.swing.JPanel toolbar_menu;
    // End of variables declaration//GEN-END:variables
}
