/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baseaplication;

import java.awt.Color;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ZevusBloxk
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Tugas
     */
    String background_toogle = "white"; 
    ImageIcon bg = new ImageIcon(getClass().getResource("/Src/Form/Netbean W Form.jpg"));
    String menu1_status = "closed";   
    String menu2_status = "closed";
    int xmouse;
    int ymouse;
    
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        load_Layout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void load_Layout(){
        background.setIcon(bg);
        close.setLocation(940, 10);
        close.setSize(50, 50);
        minimize.setLocation(830, 10);
        minimize.setSize(50, 50);
        switch_Theme.setLocation(720, 10);
        switch_Theme.setLocation(50, 50);
        drag.setLocation(0, 0);
        drag.setSize(1000, 50);
        menu1.setVisible(false);
        menu1.setLocation(0, 80);
        menu2.setLocation(30, 80);
        menu2.setVisible(false);
        menu1.setBackground(Color.decode("#ffffff"));
//        background.getComponent(0).setForeground(Color.yellow);
//        getContentPane().setForeground(Color.yellow);
    }
    void closeMenuBar(){
        menu1.setVisible(false);
        menu2.setVisible(false);
        menu1_status = "closed";
        menu2_status = "closed";
        
    }
    void exit(){
        System.exit(0);
    }
    void darkTheme(){ 
        bg = new ImageIcon(getClass().getResource("/Src/Form/Netbean B Form.jpg"));
        background.setIcon(bg);
        background_toogle = "black";
        content.setBackground(Color.decode("#5D686E"));
    }
    void lightTheme(){
        bg = new ImageIcon(getClass().getResource("/Src/Form/Netbean W Form.jpg"));
        background.setIcon(bg);
        background_toogle = "white";
        content.setBackground(Color.decode("#ffffff"));
    }

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        switch_Theme = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        menubar = new javax.swing.JToolBar();
        menu_file = new javax.swing.JButton();
        menu_edit = new javax.swing.JButton();
        menu1 = new javax.swing.JPanel();
        menuOption1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Src/Images/Logo/Logo.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 50, 40));

        switch_Theme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                switch_ThemeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                switch_ThemeMouseReleased(evt);
            }
        });
        getContentPane().add(switch_Theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, 50));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 40));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        menubar.setBackground(new java.awt.Color(255, 255, 255));
        menubar.setFloatable(false);
        menubar.setRollover(true);

        menu_file.setText("File");
        menu_file.setFocusable(false);
        menu_file.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_file.setMinimumSize(new java.awt.Dimension(40, 21));
        menu_file.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fileActionPerformed(evt);
            }
        });
        menubar.add(menu_file);

        menu_edit.setText("Edit");
        menu_edit.setFocusable(false);
        menu_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_edit.setMinimumSize(new java.awt.Dimension(40, 21));
        menu_edit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_editActionPerformed(evt);
            }
        });
        menubar.add(menu_edit);

        getContentPane().add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 30));

        menu1.setBackground(new java.awt.Color(255, 255, 255));
        menu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menuOption1.setBackground(new java.awt.Color(255, 255, 255));
        menuOption1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuOption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuOption1MouseReleased(evt);
            }
        });
        menuOption1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Exit");
        menuOption1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("alt+f4");
        menuOption1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuOption1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addComponent(menuOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );

        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 140));

        menu2.setBackground(new java.awt.Color(255, 255, 255));
        menu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 140));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 620));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Form/Netbean W Form.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fileActionPerformed
        // TODO add your handling code here:
        menu2_status = "closed";
        menu2.setVisible(false);
        if (menu1_status == "closed") {
            menu1.setVisible(true);
            menu1_status = "opened";
        } else {
            menu1.setVisible(false);
            menu1_status = "closed";
        }
    }//GEN-LAST:event_menu_fileActionPerformed

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_dragMouseDragged

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_closeMouseReleased

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMousePressed

    private void switch_ThemeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_ThemeMouseReleased
        // TODO add your handling code here:
        closeMenuBar();
        if (background_toogle == "white") {
            darkTheme();
        }else if (background_toogle == "black") {
            lightTheme();
        }
    }//GEN-LAST:event_switch_ThemeMouseReleased

    private void switch_ThemeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch_ThemeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_switch_ThemeMousePressed

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
        // TODO add your handling code here:
        this.setExtendedState(MainMenu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void menu_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_editActionPerformed
        // TODO add your handling code here:
        menu1_status = "closed";
        menu1.setVisible(false);
        if (menu2_status == "closed") {
            menu2.setVisible(true);
            menu2_status = "opened";

        } else {
            menu2.setVisible(false);
            menu2_status = "closed";
        }
    }//GEN-LAST:event_menu_editActionPerformed

    private void menuOption1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOption1MouseReleased
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_menuOption1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JPanel content;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menuOption1;
    private javax.swing.JButton menu_edit;
    private javax.swing.JButton menu_file;
    private javax.swing.JToolBar menubar;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel switch_Theme;
    // End of variables declaration//GEN-END:variables
}
